### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by konarkmodi** [ianozsvald/twitter_networkx_concept_map#1]
1. Need to add nltk as requirement too.
2. Should'nt numpy be before matplotlib in the reuirement list ?

**Comment by ianozsvald** [comment]
Agreed on both. If you've never done a pull request before I'd be happy to
receive one, if not I can do the fix easily.

**Comment by konarkmodi** [comment]
I'll issue a pull request for this.

**Comment by ianozsvald** [comment]
Super cool :-)

**Comment by konarkmodi** [comment]
Sent a PR for the same :
https://github.com/ianozsvald/twitter_networkx_concept_map/pull/2
